// Generated by CoffeeScript 1.6.3
(function() {
  window.Storage || (window.Storage = {});

  window.Storage.Local = (function() {
    function Local(prefix) {
      this.prefix = prefix;
    }

    Local.prototype.put = function(key, value) {
      return localStorage[this.prefix + key] = value;
    };

    Local.prototype.has = function(key) {
      return localStorage[this.prefix + key] != null;
    };

    Local.prototype.get = function(key) {
      if (this.has(key)) {
        return localStorage[this.prefix + key];
      }
      return null;
    };

    Local.prototype.forget = function(key) {
      return localStorage.removeItem(this.prefix + key);
    };

    return Local;

  })();

}).call(this);
