// Generated by CoffeeScript 1.6.3
(function() {
  var _base;

  window.RTC || (window.RTC = {});

  (_base = window.RTC).Peer || (_base.Peer = {});

  window.RTC.Peer.Peer = (function() {
    function Peer(name) {
      this.name = name;
    }

    return Peer;

  })();

}).call(this);
