// Generated by CoffeeScript 1.6.3
(function() {
  var connection, localVideo, remoteVideo, videoStream;

  localVideo = document.querySelector('#local');

  remoteVideo = document.querySelector('#remote');

  connection = new RTC.PeerConnection;

  videoStream = new RTC.VideoStream(function() {
    localVideo.src = videoStream.getSource();
    localVideo.play();
    return connection.addStream(videoStream);
  });

}).call(this);
