// Generated by CoffeeScript 1.6.3
(function() {
  window.Social || (window.Social = {});

  window.Social.User = (function() {
    function User(options) {
      if (options == null) {
        options = {};
      }
      this.peerID = this.generatePeerID();
      this.peer = new Peer(this.peerID, options);
    }

    User.prototype.call = function(remote, stream) {
      var call;
      return call = this.peer.call(remote.peerID, stream);
    };

    User.prototype.send = function(remote, message) {
      return this.peer.send(remote.peerID, message);
    };

    User.prototype.broadcast = function(message) {
      var remote, _i, _len, _ref, _results;
      _ref = this.connections;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        remote = _ref[_i];
        _results.push(this.send(remote, message));
      }
      return _results;
    };

    User.prototype.generatePeerID = function() {
      return Math.random().toString(36).substr(2, 10);
    };

    return User;

  })();

}).call(this);
