// Generated by CoffeeScript 1.6.3
(function() {
  window.Social || (window.Social = {});

  window.Social.Video = (function() {
    function Video(selector) {
      var self;
      self = this;
      this.video = document.querySelector('video[data-stream="local"]');
      this.stream = new RTC.AudioVideoStream(function() {
        self.video.src = self.stream.getSource();
        return self.video.play();
      });
      self.video.addEventListener('loadedmetadata', (function() {
        return self.resize();
      }), false);
    }

    Video.prototype.resize = function() {
      var video, videoRatio;
      video = this.video;
      videoRatio = video.videoWidth / video.videoHeight;
      if (videoRatio >= 1) {
        video.style.width = (video.offsetWidth * videoRatio) + 'px';
        return video.style.left = ((video.parentNode.offsetWidth - video.offsetWidth) / 2) + 'px';
      } else {
        video.style.height = (video.offsetHeight * videoRatio) + 'px';
        return video.style.top = ((video.parentNode.offsetHeight - video.offsetHeight) / 2) + 'px';
      }
    };

    return Video;

  })();

}).call(this);
