// Generated by CoffeeScript 1.6.3
(function() {
  var Logger;

  Logger = (function() {
    function Logger() {}

    Logger.prototype.levels = {
      none: 0,
      error: 1,
      log: 2,
      trace: 3
    };

    Logger.prototype.setLevel = function(level) {
      this.level = level;
    };

    Logger.prototype.trace = function(text) {
      if (this.level >= this.levels.trace) {
        return console.log((performance.now() / 1000).toFixed(3) + ": " + text);
      }
    };

    Logger.prototype.log = function(thing) {
      if (this.level >= this.levels.log) {
        return console.log(thing);
      }
    };

    Logger.prototype.error = function(text) {
      if (this.level >= this.levels.error) {
        return console.error((performance.now() / 1000).toFixed(3) + ": " + text);
      }
    };

    return Logger;

  })();

  window.Logger = new Logger;

  window.Logger.setLevel(window.Logger.levels.trace);

}).call(this);
