// Generated by CoffeeScript 1.6.3
(function() {
  var _base,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.RTC || (window.RTC = {});

  (_base = window.RTC).Connection || (_base.Connection = {});

  window.RTC.Connection.Local = (function(_super) {
    __extends(Local, _super);

    function Local(local, remote) {
      Local.__super__.constructor.call(this, local, remote);
    }

    return Local;

  })(window.RTC.Connection.Connection);

}).call(this);
