// Generated by CoffeeScript 1.6.3
(function() {
  var _base, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.RTC || (window.RTC = {});

  (_base = window.RTC).Connection || (_base.Connection = {});

  window.RTC.Connection.Remote = (function(_super) {
    __extends(Remote, _super);

    function Remote() {
      _ref = Remote.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Remote.prototype.createAnswer = function(answer) {
      return this.conn.createAnswer(answer);
    };

    return Remote;

  })(window.RTC.Connection.Connection);

}).call(this);
